import os
from typing import List

def save_pipewire_configuration(sinks: List[str], default_profile: str = "surround_5_1"):
    """Write PipeWire Pulse config drop-in for permanent system startup."""
    config_dir = os.path.expanduser("~/.config/pipewire/pipewire-pulse.conf.d")
    os.makedirs(config_dir, exist_ok=True)
    
    slaves_str = ",".join(sinks)
    
    conf_content = f"""# Auto-generated by monitor-soundstage
pulse.cmd = [
    {{ cmd = "load-module" args = "module-combine-sink sink_name=Surround_5_1_Monitors channels=6 channel_map=front-left,front-right,front-center,lfe,rear-left,rear-right sink_properties=device.description=\\"All Monitors (5.1 Surround Sound)\\" slaves={slaves_str}" flags = [ nofail ] }}
    {{ cmd = "load-module" args = "module-combine-sink sink_name=All_Monitors sink_properties=device.description=\\"All Monitors (Unified Stereo)\\" slaves={slaves_str}" flags = [ nofail ] }}
]
"""
    with open(os.path.join(config_dir, "50-all-monitors-combined.conf"), "w") as f:
        f.write(conf_content)
        
    # Write autostart script
    bin_dir = os.path.expanduser("~/.local/bin")
    os.makedirs(bin_dir, exist_ok=True)
    sh_path = os.path.join(bin_dir, "setup-monitor-audio.sh")
    
    vol_lines = "\n".join([f"pactl set-sink-volume {s} 90% 2>/dev/null" for s in sinks])
    default_sink = "Surround_5_1_Monitors" if default_profile == "surround_5_1" else "All_Monitors"
    
    script_content = f"""#!/bin/bash
# Multi-Monitor Audio Calibrator (monitor-soundstage)
{vol_lines}
pactl set-default-sink {default_sink} 2>/dev/null
pactl set-sink-volume {default_sink} 20% 2>/dev/null
"""
    with open(sh_path, "w") as f:
        f.write(script_content)
    os.chmod(sh_path, 0o755)
    
    # Desktop autostart
    autostart_dir = os.path.expanduser("~/.config/autostart")
    os.makedirs(autostart_dir, exist_ok=True)
    desktop_file = os.path.join(autostart_dir, "monitor-audio-setup.desktop")
    with open(desktop_file, "w") as f:
        f.write(f"""[Desktop Entry]
Type=Application
Name=Multi-Monitor Audio Calibration
Exec={sh_path}
X-KDE-autostart-phase=2
""")
